# Generated by Django 3.0.5 on 2020-06-24 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='lat',
            field=models.DecimalField(decimal_places=8, default=39.73915, max_digits=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='lng',
            field=models.DecimalField(decimal_places=8, default=-104.9847, max_digits=11),
            preserve_default=False,
        ),
    ]
