# Generated by Django 3.0.5 on 2020-06-24 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200624_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='lng',
            field=models.DecimalField(decimal_places=8, max_digits=12),
        ),
    ]
