# Generated by Django 3.0.5 on 2020-06-24 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_gameinstance_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameinstance',
            name='details',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
